export default {
  addresses: [],
  cart: {},
  payment: {},
  orderHistory: [],
  order: {},
  productMedia: {},
  measurements: [],
  partnerRegister: {},
  partnerLogin: {},
  offerTileOffers: [],
  wishlist: [],
  categories: ["hii"],
  inProgressAddtocartProducts: [],
  ordersWithStatusHistory: [],
  recentOrderItems: [],
  submittedOrderItems: [],
  recentReviews: [],
  quotes: [],
  quote: {},
  createQuote: {},
  categoryDetail: {},
  designType: {},
  recentQuotes: [],
  inProgressUploadImgs: [],
  codes: [],
};
